language: go

go:
  - 1.13.x
  - tip

before_script:
  - go get -t -v github.com/si9ma/gen/...

script:
  - go build main.go

notifications:
  email:
    recipients: smallnest@gmail.com
    on_success: change
    on_failure: always
